apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: exam
spec:
  selector:
    app: backend
  ports:
    - name : http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: exam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: podobox/springboot:1.0
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "0.2"
              memory: "200Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service.exam:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: username

            # - name: DB_SERVER
            #   value: mysql-service.exam
            #   # valueFrom:
            #   #   configMapKeyRef:
            #   #     name:  db-config
            #   #     key: mysql-server
            # - name: DB_NAME
            #   value: testdb
            #   # valueFrom:
            #   #   configMapKeyRef:
            #   #     name: db-config
            #   #     key: mysql-database-name