apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  password: cm9vdAo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: exam
data:
  mysql-server: "mysql-service"
  mysql-database-name: "testdb"
  username: "root"